# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "ensimag-nificent-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Eduard Occhipinti"]
license = "Unlicense"
description = "Template for the ENSIMAG thesis at Université Grenoble Alpes, INP"
# homepage = ""
repository = "https://github.com/eduardz1/ensimag-nificent-thesis"
keywords = []
categories = ["thesis"]
disciplines = ["computer-science"]
# compiler = ""
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
